baseurl = "https://jeremp.github.io/"
languageCode = "fr"
title = "Jeremy Passeron"
theme = "purehugo"
Paginate = 10

[params]
  twitterName = "dragos_plesca"
  githubName = "dplesca"
  description = "Java/Web/Iot Develop3r"
  google_analytics = "UA-68415224-1"
 